
GET http://localhost:8080/contacts 

###
GET http://localhost:8080/contacts/65ac80700ba1eeb77fb8633f
###
GET http://localhost:8080/contacts/65ac80e70ba1eeb77fb86340
###
GET http://localhost:8080/contacts/65ac81000ba1eeb77fb86341

### CREATE
POST http://localhost:8080/contacts HTTP/1.1
content-type: application/json

{
    "firstName" : "David",
    "lastName" : "Facer",
    "email" : "facerdave@cei.edu",
    "favoriteColor" : "blue",
    "birthday" : "July 13, 1968"
}

### PUT
PUT http://localhost:8080/contacts/65ac80700ba1eeb77fb8633f HTTP/1.1
content-type: application/json

{
    "firstName": "Logan",
    "lastName": "Ochs",
    "email": "ochslogan@gmail.com",
    "favoriteColor": "green",
    "birthday": "March 30, 1998"
}

### DELETE
DELETE http://localhost:8080/contacts/65ac80e70ba1eeb77fb86340 HTTP/1.1

###
GET https://cse-341-winter24.onrender.com/contacts

### 
POST https://cse-341-winter24.onrender.com/contacts HTTP1.1
content-type: application/json

{
    "firstName" : "David",
    "lastName" : "Facer",
    "email" : "facerdave@cei.edu",
    "favoriteColor" : "blue",
    "birthday" : "July 13, 1968"
}

###
PUT https://cse-341-winter24.onrender.com/contacts/65ac80700ba1eeb77fb8633f HTTP1.1
content-type: application/json

{
   "firstName": "Logan",
    "lastName": "Ochs",
    "email": "ochslogan@gmail.com",
    "favoriteColor": "green",
    "birthday": "March 30, 1998"
}

###
DELETE https://cse-341-winter24.onrender.com/contacts/65ac80e70ba1eeb77fb86340 HTTP/1.1


